config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'contact#index'
  post 'contact', to: "contact#mail"

  resources :posts do
    member do
      resources :comments
    end
  end


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'pages/index'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable
  has_many :comments

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def mail

  if params[:contact]
    email =  params[:contact][:email]
    message = params[:contact][:message]

    if email.present? || message.present?
      # Tell the UserMailer to send a welcome email after save
      ContactMailer.send_contact_email(email, message).deliver_now
      redirect_to '/contact', notice: 'Email sent!'
    else
      flash[:warning] = "Please fill out the form"
      redirect_to '/contact'
    end
  end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comments = Comment.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for (comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user.email %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/contact/index.html.erb
<div class="container center1">
  <div class="row">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% elsif flash[:warning]%>
      <div class="alert alert-danger"><%= flash[:warning] %></div>
    <% end %>


    <h1>Contact Us</h1>

    <%= form_for(:contact) do |f| %>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

      <div class="field">
        <%= f.label :message %>
        <%= f.text_field :message %>
      </div>

      <div class="actions">
        <%= f.submit 'Send Message'%>
      </div>
    <% end %>
    </div>
</div>

app/views/contact/mail.html.erb
<h1>Contact#mail</h1>
<p>Find me in app/views/contact/mail.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lambnation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container center">
  <h1>Welcome Yung Lamb</h1>
</div>
<div class="container center">
  <img src="https://image.freepik.com/free-icon/christian-lamb_318-100624.jpg" alt="">
</div>

app/views/partials/_nav.html.erb
<!--
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" id="white"href="#">Yung Lamb</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li id="white">
          <%=link_to 'Posts', posts_path, :id => "white"%>
        </li>
        <% if user_signed_in? %>
        <li id="white"><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :id => "white" %></li>
        <% else %>
        <li id="white"><%= link_to 'Sign In', new_user_session_path, :id => "white"%></li>
        <li id="white"><%= link_to 'Register', new_user_registration_path, :id => "white" %></li>
        <% end %>
      </ul>
    </div>
  </div>

</nav> -->

<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <%= link_to root_path, :class => "nav-item" do %>
          <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/122811-200.png" alt="Bulma logo">
      <% end %>

      <%=link_to 'Posts', posts_path, :class => "nav-item is-tab is-hidden-mobile"%>
      <%=link_to 'New Posts', new_post_path, :class => "nav-item is-tab is-hidden-mobile"%>
      <%=link_to 'Contact', contact_path, :class => "nav-item is-tab is-hidden-mobile"%>
    </div>
    <span class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>
    <div class="nav-right nav-menu">

      <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "nav-item is-tab" %>
      <% else %>
      <%= link_to 'Sign In', new_user_session_path, :class => "nav-item is-tab"%>
      <%= link_to 'Register', new_user_registration_path, :class => "nav-item is-tab" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<div class="container center">
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container center">
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container center">
<h1>Posts</h1>
</div>

<div class="container center">

<% @posts.each do |post| %>

  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        <%= post.title %>
      </p>
      <a class="card-header-icon">
        <span class="icon">
          <i class="fa fa-angle-down"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        <%= post.content %>
        <br>
        <small><%= post.created_at %></small>
        <br>
        <small><%= post.user.email %></small>
      </div>
    </div>
    <footer class="card-footer">
      <%= link_to 'Show', post, :class=> "card-footer-item"%>
      <%= link_to 'Edit', edit_post_path(post), :class=> "card-footer-item"%>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "card-footer-item"%>
    </footer>
  </div>

<% end %>

</div>



<!-- <div class="container">
  <% @posts.each do |post| %>
      <%= post.user.email %>
      <br>
      <%= post.title %>
      <br>
      <%= post.content %>
      <br>
  <% end %>

  <%= link_to 'New Post', new_post_path %>
</div> -->

app/views/posts/new.html.erb
<div class="container center">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="wrapper">

<div class="card">
  <div class="card-content">
    <p class="title">
      <%= @post.content %>
    </p>
    <p class="subtitle">
      <%= @post.user.email %>
    </p>
    <%= social_share_button_tag(@post.title) %>
  </div>
  <footer class="card-footer">
    <p class="card-footer-item">
      <span>
        <%= link_to 'Edit', edit_post_path(@post) %>
      </span>
    </p>
    <p class="card-footer-item">
      <span>
        <%= link_to 'Back', posts_path %>
      </span>
    </p>
  </footer>
</div>

<div class="box">
  <% @comments.each do |comment| %>
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <small><%= comment.user.email %></small>
          <br>
          <%= comment.content %>
        </p>
      </div>
    </div>
  </article>
  <% end %>
  <%= render 'comments/form', comment: @comment%>
</div>

</div>